<?php

/**
 * Implementation of hook_help().
 */
function user_relationships_services_help($path, $arg) {
  switch ($path) {
    case 'admin/help#services_user':
      return '<p>'. t('Provides user relationship methods to services applications. Requires services.module.') .'</p>';
    case 'admin/modules#description':
      return t('Provides user relationship methods to services applications. Requires services.module.');
  }
}

/**
 * Implementation of hook_service().
 */
function user_relationships_services_service() {
  return array(
    array(
      '#method' => 'user_relationships.types',
      '#callback' => 'user_relationships_services_types',
      '#access callback' => '_user_relationships_services_access',
      '#file' => array(
        'file' => 'inc',
        'module' => 'user_relationships_services'
      ),
      '#args' => array(),
      '#return' => 'array',
      '#help' => t('Returns an array of relationship types.'),
    ),
    array(
      '#method' => 'user_relationships.list',
      '#callback' => 'user_relationships_services_list',
      '#access callback'  => '_user_relationships_services_access',
      '#file' => array(
        'file' => 'inc',
        'module' => 'user_relationships_services'
      ),
      '#args' => array(),
      '#return' => 'array',
      '#help' => t('Returns an array of user objects with relationship information to the current user.'),
    ),
    array(
      '#method' => 'user_relationships.request',
      '#callback' => 'user_relationships_services_request',
      '#access callback'  => '_user_relationships_services_access',
      '#file' => array(
        'file' => 'inc',
        'module' => 'user_relationships_services'
      ),
      '#args' => array(
        array(
          '#name' => 'mail',
          '#type' => 'string',
          '#description' => t('Email address of the user being requested.'),
        ),
        array(
          '#name' => 'type',
          '#type' => 'string',
          '#description' => t('Name of the relationship type to create.'),
        ),
      ),
      '#return' => 'array',
      '#help' => t('Request a relationship with another user.'),
    ),
    array(
      '#method' => 'user_relationships.approve',
      '#callback' => 'user_relationships_services_approve',
      '#access callback'  => '_user_relationships_services_access',
      '#file' => array(
        'file' => 'inc',
        'module' => 'user_relationships_services'
      ),
      '#args' => array(
        array(
          '#name' => 'rid',
          '#type' => 'int',
          '#description' => t('Relationship ID to approve.'),
        ),
      ),
      '#return' => 'array',
      '#help' => t('Approves a requested relationship.'),
    ),
    array(
      '#method' => 'user_relationships.remind',
      '#callback' => 'user_relationships_services_remind',
      '#access callback'  => '_user_relationships_services_access',
      '#file' => array(
        'file' => 'inc',
        'module' => 'user_relationships_services'
      ),
      '#args' => array(
        array(
          '#name' => 'rid',
          '#type' => 'int',
          '#description' => t('Relationship ID for reminding user.'),
        ),
      ),
      '#return' => 'array',
      '#help' => t('Approves a requested relationship.'),
    ),
    array(
      '#method' => 'user_relationships.delete',
      '#callback' => 'user_relationships_services_delete',
      '#access callback'  => '_user_relationships_services_access',
      '#file' => array(
        'file' => 'inc',
        'module' => 'user_relationships_services'
      ),
      '#args' => array(
        array(
          '#name' => 'rid',
          '#type' => 'int',
          '#description' => t('Relationship ID to delete.'),
        ),
        array(
          '#name' => 'reason',
          '#type' => 'string',
          '#description' => t('Reason for deletion (cancel, disapprove or remove).'),
        ),
      ),
      '#return' => 'array',
      '#help' => t('Delete an existing or pending relationship.'),
    ),
  );
}

/**
 * Check if the user is allowed to use user_relationships.
 */
function _user_relationships_services_access() {
  return TRUE;
}
